Docker clean up (#32)

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,18 +1,22 @@
+# .github/workflows/deploy.yml
+
 name: Deploy to DigitalOcean DEV
+
 on:
   push:
     branches:
       - 'dev'
   workflow_dispatch:
-    inputs: 
+    inputs:
       build_and_push_docker_images:
-        description: 'Build and push Docker images'
+        description: 'Docker building options'
         type: choice
         options:
-          - 'true'
-          - 'false'
-        default: 'true'
-        
+          - 'build'
+          - 'push'
+          - 'build and push'
+        default: 'build and push'
+      
       copy_files_to_remote:
         description: 'Copy files to remote server'
         type: choice
@@ -20,7 +24,7 @@ on:
           - 'true'
           - 'false'
         default: 'true'
-        
+      
       restart_services:
         description: 'Restart services on remote server'
         type: choice
@@ -36,64 +40,118 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Set up Docker Build
-        uses: docker/setup-buildx-action@v1
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Set up .env_build file from repository
+        run: |
+          # Ensure the .env_build file exists in the repository
+          if [ ! -f .env_build ]; then
+            echo ".env_build file not found in the repository. Exiting."
+            exit 1
+          fi
+
+      - name: Inject sensitive variables into .env_build
+        run: |
+          # Append sensitive variables from GitHub Secrets to .env_build
+          echo "SA_PASSWORD=${{ secrets.SA_PASSWORD }}" >> .env_build
+
+      - name: Set environment variables based on trigger type
+        id: set_vars
+        run: |
+          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
+            echo "Triggered by workflow_dispatch"
+            echo "BUILD_AND_PUSH=${{ github.event.inputs.build_and_push_docker_images }}" >> $GITHUB_ENV
+            echo "COPY_FILES=${{ github.event.inputs.copy_files_to_remote }}" >> $GITHUB_ENV
+            echo "RESTART_SERVICES=${{ github.event.inputs.restart_services }}" >> $GITHUB_ENV
+          else
+            echo "Triggered by push"
+            # Set default values for automatic triggers
+            echo "BUILD_AND_PUSH=build and push" >> $GITHUB_ENV
+            echo "COPY_FILES=true" >> $GITHUB_ENV
+            echo "RESTART_SERVICES=true" >> $GITHUB_ENV
+          fi
+
+      - name: Export environment variables from .env_build
+        run: |
+          # Export all variables from .env_build to the environment
+          set -a
+          source .env_build
+          set +a
+          
+          # Export specific variables to GitHub Actions environment
+          echo "DEV_DOCKER_CONFIGURATION=${DEV_DOCKER_CONFIGURATION}" >> $GITHUB_ENV
+          echo "DEV_API_URL=${DEV_API_URL}" >> $GITHUB_ENV
+          echo "COMMIT_NAME=${COMMIT_NAME}" >> $GITHUB_ENV
+          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
+          echo "SA_PASSWORD=${SA_PASSWORD}" >> $GITHUB_ENV
 
       - name: Login to DigitalOcean Container Registry
         run: echo "${{ secrets.DIGITAL_OCEAN_DOCKER_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DIGITAL_OCEAN_USERNAME }} --password-stdin
 
-      - if: ${{ github.event.inputs.build_and_push_docker_images == 'true' }}
-        name: Build and push Docker images
+      - name: Determine Build and Push Actions
+        id: determine_actions
         run: |
-          docker build . --no-cache -f ./AutoNaJuz.Api/Dockerfile -t registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
-          docker build . --no-cache -f ./AutoNaJuz.Web/Dockerfile -t registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug
-          docker push registry.digitalocean.com/auto-na-juz/auto-na-juz-api:debug
-          docker push registry.digitalocean.com/auto-na-juz/auto-na-juz-web:debug
-          
+          echo "BUILD_AND_PUSH=${BUILD_AND_PUSH}" >> $GITHUB_ENV
+          echo "COPY_FILES=${COPY_FILES}" >> $GITHUB_ENV
+          echo "RESTART_SERVICES=${RESTART_SERVICES}" >> $GITHUB_ENV
+
+      - if: env.BUILD_AND_PUSH == 'build' || env.BUILD_AND_PUSH == 'build and push'
+        name: Build AutoNaJuzApi Docker Image
+        run: |
+          docker build . \
+            -f ./AutoNaJuz.Api/Dockerfile \
+            --build-arg configuration=${DEV_DOCKER_CONFIGURATION} \
+            --build-arg DEV_API_URL=${DEV_API_URL} \
+            -t registry.digitalocean.com/auto-na-juz/auto-na-juz-api:${DEV_DOCKER_CONFIGURATION,,} \
+
+      - if: env.BUILD_AND_PUSH == 'build' || env.BUILD_AND_PUSH == 'build and push'
+        name: Build AutoNaJuzWeb Docker Image
+        run: |
+          docker build . \
+            -f ./AutoNaJuz.Web/Dockerfile \
+            --build-arg configuration=${DEV_DOCKER_CONFIGURATION} \
+            --build-arg DEV_API_URL=${DEV_API_URL} \
+            -t registry.digitalocean.com/auto-na-juz/auto-na-juz-web:${DEV_DOCKER_CONFIGURATION,,} \
+
+      - if: env.BUILD_AND_PUSH == 'push' || env.BUILD_AND_PUSH == 'build and push'
+        name: Push AutoNaJuzApi Docker Image
+        run: |
+          docker push registry.digitalocean.com/auto-na-juz/auto-na-juz-api:${DEV_DOCKER_CONFIGURATION,,}
+
+      - if: env.BUILD_AND_PUSH == 'push' || env.BUILD_AND_PUSH == 'build and push'
+        name: Push AutoNaJuzWeb Docker Image
+        run: |
+          docker push registry.digitalocean.com/auto-na-juz/auto-na-juz-web:${DEV_DOCKER_CONFIGURATION,,}
+
       - name: Set up SSH for rsync
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          # Add DigitalOcean host to known_hosts to prevent host key verification
-          ssh-keyscan -H ${{ secrets.DIGITAL_OCEAN_SSH_HOST }} >> ~/.ssh/known_hosts
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
 
-      - if: ${{ github.event.inputs.copy_files_to_remote == 'true' }}
-        name: Copy nginx and docker-compose.dev directories
+      - if: env.COPY_FILES == 'true'
+        name: Copy files to remote server
         run: |
-          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" ./nginx/ ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}@${{ secrets.DIGITAL_OCEAN_SSH_HOST }}:/tmp/nginx/
-          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" ./docker-compose.dev/ ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}@${{ secrets.DIGITAL_OCEAN_SSH_HOST }}:/tmp/docker-compose.dev/
+          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" .env_build ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}@${{ secrets.DIGITAL_OCEAN_SSH_HOST }}:/app/.env_build
+          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" docker-compose.yml ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}@${{ secrets.DIGITAL_OCEAN_SSH_HOST }}:/app/docker-compose.yml
+          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" nginx/ ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}@${{ secrets.DIGITAL_OCEAN_SSH_HOST }}:/app/nginx/
 
-      - name: Deploy to DigitalOcean
-        uses: appleboy/ssh-action@master
+      - if: env.RESTART_SERVICES == 'true'
+        name: Deploy to DigitalOcean
+        uses: appleboy/ssh-action@v0.1.4
         with:
           host: ${{ secrets.DIGITAL_OCEAN_SSH_HOST }}
           username: ${{ secrets.DIGITAL_OCEAN_SSH_USERNAME }}
           key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
           script: |
-            
-            if [${{ github.event.inputs.copy_files_to_remote }} == 'true']; then
-              # Ensure /app directory exists
-              mkdir -p /app
+            cd /app
+            docker pull registry.digitalocean.com/auto-na-juz/auto-na-juz-api:${DEV_DOCKER_CONFIGURATION,,}
+            docker pull registry.digitalocean.com/auto-na-juz/auto-na-juz-web:${DEV_DOCKER_CONFIGURATION,,}
 
-              # Move nginx/ directory to /app/nginx
-              sudo mv /tmp/nginx /app/nginx
+            docker compose stop autonajuzapi autonajuzweb
+            docker compose rm -f autonajuzapi autonajuzweb
 
-              # Move docker-compose.dev files to /app
-              sudo mv /tmp/docker-compose.dev/* /app/
-              sudo rm -rf /tmp/docker-compose.dev
-            fi
-            
-            if [${{ github.event.inputs.restart_services }} == 'true']; then
-              # Change directory to /app
-              cd /app
-              # Pull the latest images
-              docker compose pull
+            docker compose up -d --no-deps --force-recreate autonajuzapi autonajuzweb
 
-              # Stop and remove only the API and web containers
-              docker compose -f docker-compose.yml -f docker-compose.dev.yml stop autonajuzapi autonajuzweb
-              docker compose -f docker-compose.yml -f docker-compose.dev.yml rm --force autonajuzapi autonajuzweb
-
-              # Recreate the API and web containers with the latest images
-              docker compose -f docker-compose.yml -f docker-compose.dev.yml --profile debug up -d --no-deps --force-recreate autonajuzapi autonajuzweb
-            fi
+            # Optionally, restart nginx and certbot if needed
+            docker compose restart nginx certbot
